config/routes.rb
Tsohar::Application.routes.draw do

  controller :sessions do
    get '/login' => :new
    post '/login' => :create
  end

  match 'logout' => 'sessions#destroy', :as => :logout

  root :to => "projects#index"

  resources :users

  resources :projects do
    match 'add_member' => 'members#add', :as => :add_member
    resources :tasks do
      resources :task_locks, :only => [:create]
    end
    resources :members
end

end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :project
  
  has_many :task_locks, :dependent => :delete_all
  
  attr_accessible :name, :description, :priority, :status, :deadline, :comment
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_filter :authorize, :except => :show
  before_filter :can_add?, :except => :show
  
  # GET /tasks/1
  # GET /tasks/1.xml
  def show
    @project = Project.find(params[:project_id])
    @task = @project.tasks.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @task }
    end
  end

  # GET /tasks/new
  # GET /tasks/new.xml
  def new
    @project = Project.find(params[:project_id])
    @task = @project.tasks.new
  
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @task }
    end
  end

  # GET /tasks/1/edit
  def edit
    @project = Project.find(params[:project_id])
    @task = @project.tasks.find(params[:id])
  end

  # POST /tasks
  # POST /tasks.xml
  def create
    @project = Project.find(params[:project_id])
    @task = @project.tasks.new(params[:task])

    respond_to do |format|
      if @task.save
        format.html { redirect_to(@project, :notice => 'Task was successfully created.') }
        format.xml  { render :xml => @task, :status => :created, :location => @task }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @task.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /tasks/1
  # PUT /tasks/1.xml
  def update
    @project = Project.find(params[:project_id])
    @task = @project.tasks.find(params[:id])
    
    respond_to do |format|
      if @task.update_attributes(params[:task])
        format.html { redirect_to(@project, :notice => 'Task was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @task.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.xml
  def destroy
    @project = Project.find(params[:project_id])
    @task = @project.tasks.find(params[:id])
    @task.destroy

    respond_to do |format|
      format.html { redirect_to(@project) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_for([@project, @task]) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :priority %><br />
    <%= f.select(:priority, 1.upto(5).to_a) %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.select(:status, ["pending", "completed"]) %>
  </div>
  <div class="field">
    <%= f.label :deadline %><br />
    <%= f.datetime_select :deadline %>
  </div>
  <div class="field">
    <%= f.label :comment %><br />
    <%= f.text_field :comment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render 'form' %>

<%= link_to 'Show', project_task_path(@project) %> |
<%= link_to 'Back', project_path(@project) %>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render 'form' %>

<%= link_to 'Back', project_path(@project) %>

app/views/tasks/show.html.erb
<p>
  <b>Name:</b>
  <%= @task.name %>
</p>

<p>
  <b>Description:</b>
  <%= @task.description %>
</p>

<p>
  <b>Priority:</b>
  <%= @task.priority %>
</p>

<p>
  <b>Status:</b>
  <%= @task.status %>
</p>

<p>
  <b>Deadline:</b>
  <%= @task.deadline %>
</p>

<p>
  <b>Comment:</b>
  <%= @task.comment %>
</p>

<% unless @task.task_locks.empty? %>
Task allocated to:
<% @task.task_locks.each do |lock| %>
<p><%= lock.user.username %></p>
<% end %>
<% end %>

<%= if_project_admin @project do %>
<%= form_for [@project, @task, @task.task_locks.new], :task_id => @task.id do |f| %>
	<%= f.select(:user_id, @project.project_members.collect {|u| [u.username, u.id]}) %>
	<%= f.submit "Allocate task" %>
<% end %>

<%= link_to 'Edit', edit_project_task_path(@project, @task) %> |
<%= link_to 'Destroy', project_task_path(@project, @task), :confirm => 'Are you sure?', :method => :delete %> |
<% end %>
<%= link_to 'Back', project_path(@project) %>