config/routes.rb
Tsohar::Application.routes.draw do

  controller :sessions do
    get '/login' => :new
    post '/login' => :create
  end

  match 'logout' => 'sessions#destroy', :as => :logout

  root :to => "projects#index"

  resources :users

  resources :projects do
    match 'add_member' => 'members#add', :as => :add_member
    resources :tasks do
      resources :task_locks, :only => [:create]
    end
    resources :members
end

end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :members, :dependent => :delete_all
  has_many :project_members, :through => :members, :source => :user
  has_many :tasks, :dependent => :delete_all
  
  validates_presence_of :name, :deadline
  
  attr_accessible :name, :description, :url, :deadline, :visibility
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :authorize, :only => [:new, :create, :edit, :update, :destroy]
  before_filter :can_access?, :only => [:show, :edit, :update, :destroy]
  before_filter :can_modify?, :only => [:edit, :update, :destroy]
  before_filter :is_creator?, :only => [:destroy]
  
  # GET /projects
  # GET /projects.xml
  def index
    @projects = Project.all(:conditions => {:visibility => "Public"})

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.xml
  def show
    @project = Project.find(params[:id])
    @members = @project.members.all
    @tasks = @project.tasks.all(:order => "status, priority, deadline")

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => [@project, @members, @tasks] }
    end
  end

  # GET /projects/new
  # GET /projects/new.xml
  def new
    @project = Project.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
  end

  # POST /projects
  # POST /projects.xml
  def create
    @project = Project.new(params[:project])
    user = User.find_by_id(session[:user_id])

    respond_to do |format|
      if @project.save
        @project.members.create(:user_id => user.id, :member_role_id => MemberRole.find_or_create_by_role("creator").id)
        format.html { redirect_to(@project, :notice => 'Project was successfully created.') }
        format.xml  { render :xml => @project, :status => :created, :location => @project }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @project.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.xml
  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to(@project, :notice => 'Project was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @project.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.xml
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to(projects_url) }
      format.xml  { head :ok }
    end
  end
  
  private
  
  def is_creator?
    project = Project.find(params[:id])
    member = project.members.find_by_user_id(session[:user_id])
    if member.member_role.role == "creator"
      return true
    end
    redirect_to project, :notice => "You're not allowed to destroy this project!"
  end
  
  # Redirects to root unless the project is public, or the user logged in is a member of the project
  def can_access?
    project = Project.find(params[:id])
    
    if logged_in?
      user = User.find(session[:user_id])
      unless user.projects.include?(project) or project.visibility == "Public"
        redirect_to root_url, :notice => "You're not authorized to access this project!"
      end
    elsif project.visibility != "Public"
      redirect_to root_url, :notice => "You're not authorized to access this project!"
    end
  end
  
  # Redirects to project unless the logged in user is either the creator or an administrator of the project, in which case returns true
  def can_modify?
    project = Project.find(params[:id])
    
    if logged_in?
      user = User.find(session[:user_id])
      if user.projects.include?(project)
        member = project.members.find_by_user_id(user)
        if (member.member_role.role == "creator" or member.member_role.role == "administrator")
          return true
        end
      end
    end
    redirect_to project, :notice => "You're not authorized to modify this project!"
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
  	<%= f.label :name %><br />
	<%= f.text_field :name %>
  </div>
  <div class="field">
  	<%= f.label :description %><br />
	<%= f.text_area :description %>
  </div>
  <div class="field">
  	<%= f.label :url %><br />
	<%= f.url_field :url %>
  </div>
  <div class="field">
  	<%= f.label :deadline %><br />
	<%= f.date_select :deadline %>
  </div>
  <div class="field">
  	<%= f.label :visibility %><br />
	<%= f.radio_button :visibility, "Public" %><span>Public</span>
	<%= f.radio_button :visibility, "Private" %><span>Private</span>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h1>Projektit</h1>

<br />

<% @projects.each do |project| %>
	<h2><%= project.name %></h2>
	<p><%= project.description %></p>
<table>
  <tr>
    <td><%= link_to 'Show', project %></td>
	<%= if_project_admin project do %>
    <td><%= link_to 'Edit', edit_project_path(project) %></td>
    <td><%= link_to 'Destroy', project, :confirm => 'Are you sure?', :method => :delete %></td>
	<% end %>
  </tr>
</table>
<% end %>

<br />

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<h1><%= @project.name %></h1>

<p><%= @project.description %></p>
<p>Deadline: <%= @project.deadline.strftime("%d.%m.%Y %H:%M") %></p>

<h2>Project members</h2>
<table>
	<th>Username</th>
	<th>Role</th>
	<th>E-mail</th>
	<th>Title</th>
<% @members.each do |member| %>
<tr>
	<td><%= member.user.username %></td>
	<td><%= member.member_role.role %></td>
	<td><%= member.user.email %></td>
	<td><%= member.title %></td>
</tr>
<% end %>
</table>
<%= link_to 'Show all members', project_members_path(@project) %>

<h2>Tasks</h2>
<% unless @tasks.empty? %>
<table>
	<th>Task</th>
	<th>Description</th>
	<th>Priority</th>
	<th>Status</th>
	<th>Deadline</th>
	<th></th>
<% @tasks.each do |task| %>
<tr>
	<td><%= task.name %></td>
	<td><%= task.description %></td>
	<td><%= task.priority %></td>
	<td><%= task.status %></td>
	<td><%= task.deadline %></td>
	<td><%= link_to 'Show task', project_task_path(@project, task) %></td>
</tr>
<% end %>
<% end %>
</table>
<%= if_project_admin @project do %>
<%= link_to 'New Task', new_project_task_path(@project, @task) %><br />

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Destroy', project_path(@project), :confirm => 'Are you sure?', :method => :delete %> |
<% end %>
<%= link_to 'Back', projects_path %>