config/routes.rb
Tsohar::Application.routes.draw do

  controller :sessions do
    get '/login' => :new
    post '/login' => :create
  end

  match 'logout' => 'sessions#destroy', :as => :logout

  root :to => "projects#index"

  resources :users

  resources :projects do
    match 'add_member' => 'members#add', :as => :add_member
    resources :tasks do
      resources :task_locks, :only => [:create]
    end
    resources :members
end

end

app/models/member.rb
class Member < ActiveRecord::Base
  belongs_to :member_role
  belongs_to :project
  belongs_to :user
  
  attr_accessible :user_id, :member_role_id
  validates_uniqueness_of :project_id, :scope => [:user_id], :message => "You cannot add the same user twice!"
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_filter :can_add?, :except => [:index]
  def index
    @project = Project.find(params[:project_id])
    @members = @project.members.all
  end
  
  # Collects all registered users who aren't members of the project
  def add
    @project = Project.find(params[:project_id])
    @users = User.all.collect {|user| user unless user.projects.include?(@project)}.compact!
  end
  
  def new
    @project = Project.find(params[:project_id])
    @user = User.find(params[:user_id])
    @member = @project.members.new
    
    respond_to do |format|
      format.html
    end
  end
  
  def create
    @project = Project.find(params[:project_id])
    @member = @project.members.new(params[:member])
    
    respond_to do |format|
      if @member.save
        format.html { redirect_to(@project, :notice => 'Member was successfully added.') }
      else
        format.html { render :action => "new" }
      end
    end
  end
end

app/views/members/_form.html.erb
<%= form_for([@project, @member]) do |f| %>
  <% if @member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@member.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @member.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
  	<%= f.label :member_role_id %>
	<%= f.select(:member_role_id, MemberRole.find_or_create_roles) %>
  </div>
	<%= f.hidden_field :user_id, { :value => params[:user_id] } %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/members/add.html.erb
<h2>Choose a user to add to project <%= @project.name %></h2>

<table>
  <tr>
    <th>Username</th>
    <th>Email</th>
    <th></th>
  </tr>
<% @users.each do |user| %>
<tr>
  <td><%= user.username %></td>
  <td><%= user.email %></td>
	<td><%= link_to 'add', {:controller => "members", :action => "new", :project_id => @project.id, :user_id => user.id} %></td>
</tr>
<% end %>
</table>

app/views/members/index.html.erb
<h2>Project members</h2>
<table>
	<th>Username</th>
	<th>Role</th>
	<th>E-mail</th>
	<th>Title</th>
<% @members.each do |member| %>
<tr>
	<td><%= member.user.username %></td>
	<td><%= member.member_role.role %></td>
	<td><%= member.user.email %></td>
	<td><%= member.title %></td>
</tr>
<% end %>
</table>
<%= if_project_admin @project do %><%= link_to 'Add a new member', project_add_member_path %> |<% end %>
<%= link_to 'Back', project_path(@project) %>

app/views/members/new.html.erb
<h1>Adding to the project <%= @project.name %></h1>

<%= render 'form' %>